language: java
jdk: 
- oraclejdk8

script: mvn package

cache:
  directories:
    - $HOME/.m2

deploy:
  - provider: releases
    overwrite: true
    draft: false
    api_key:
       secure: "UJUpO9IlEpBu76z3NF37zkP66TUBlRNZ7gNM9NZUifIXBs6SvYbYkHGwV3K1P6X3sILG/R6357SEf7+NFCBKcHpFNtzNjEcC12edNxYKZhsqa3CPY/5WhGemiuUvNc/bgOCdwriGYhT/O8jvD/O/zXwGcufGcJN8Mj5GxgT48OLEH3gTde3dOtTEXHqYW5supcChFM69jalsEYchUvNrFPwv3hj8mFycKGpYTTe4E5kXzezi+C13K/OF+AX6EcTpJRrzdqkqIMYNM9FAsn2p4IJLyg3PX+4XU8+zR7aGYjpJGNJ3sWN2Mnd47XIVVwyVflfItKhb/eex+BXK5sRmv+/Wo+04TsY3VLL20nfReV8X5MPO3ZWmV6oAYkQyakpchdc1s3zONrp60SbbWTuDGcsuF4emmK1hstGOjtuDmkyvys0+zrL3D7UaN3mz5sMSQKc2Cr5v9iMkkloLqAjRWU0fbSfqTR374DqKpolZfmD1iF9wqfENtG2v6w8gc4IZT+Am0UCz7QYEBc1bndbrpg8NiKea3K2aN8UXTU9Ur+n6y1fIaM2b/cAgrv7NbdGkoSN4zJRV6eAtxvVJvZyXmOABi5cnJSh9LBDEgcuLinqTxjPcB+h7REIsMIFrXbVal235AbYTFVpSMUM5rmFyLP84/F5V+T8h2GPyJiMdojI="
    file: 
    - jvmtop
    - jvmtop.jar
    skip_cleanup: false
    on:
      tags: false
      repo: strapdata/jvmtop
