language: java
jdk:
- oraclejdk8
script: mvn package
cache:
  directories:
  - "$HOME/.m2"

deploy:
- provider: releases
  overwrite: true
  draft: false
  api_key:
    secure: "wbzffDNNyYs7wuu+RKG5J1v4ei1ajwKtnroFFKCbWH9V9SlS6E4Ns4TzQbm6L42IhgdAXxyDwC+EdxrYJq0L5kgubciTx4foCYez+KvdkO1UF+PP+cTWNHS1nqVmJAtRE0AyuQr1oQsIdc1kJenIqLToyu2qN7GhDqcHkL/il8sGIb/jFwP538HEiLyPe8/HjooIITB4p/iV/mtu7cd3iNzAYJ2ZeDYVw0vkJzOWpmpLXytihF7VsF2WynTbCR025buZ2OYavvdjcjDpKHZiYPoJz8w0w1dxrXpDEkgdhKePr4GYcrtRefczLY9p/kfJP8o/Ewrk/layRhcTZNljnPS3kNgrgkeA024f6QeJQC1hl84+21AL1p3BmCUCy+KFsnqmuxOZo9VT4RgeGXAPafmLc3Je/KoRE6PueheeETtkW3D33OuHfElGg8GWqsh7fbg0h82/+lsXB4CG/uN8e7xPjICl3jOO3R6QodAjoOluLObwcYG6C4RcijVqA4id5UOBoroLyusBAsJp59PXwPdegUgMZN5+2s0x469sLC5+Icv7dH5yubuS+mPE9zT3B2naKw1qWhWIf8NiaHseaqqrnKzB7y1Se4EO52iO2fPa7xplNdnWZUw6C0XzM51d7EV3q5gzAMPgvYnxlD6G6Nac4qCWV9Cm8ro88FSyvnk="
  file:
  - jvmtop
  - jvmtop.jar
  skip_cleanup: false
  on:
    tags: false
    repo: strapdata/jvmtop

