language: java
jdk: 
- oraclejdk8

script: mvn package

cache:
  directories:
    - $HOME/.m2

deploy:
  - provider: releases
    overwrite: true
    draft: false
    api_key:
      secure: "11xA+n75AXhXbKvO8RiyVxlVtD7c0y3g6UM5G2ddvE+jzzmNhftFreveTz8POYpsK1KFFUCFV93WWA35qQoRTAecHsHb+gG0oqb8YgXda4sRLaYg9POxkvSdrKhni7Wwoi1hXFIZ9AOg04LoqeYlQ4ng+thDODi9LLM8dno5MtoSp/x3XoOiqH7t1NfUS87b48NGAQS8QY4oWJ9Uj8Y73G3T1Yg/OiBPPs8QgIFfvO2mI3WZs6I7Inec9ZTsKZ7IA9DolqGzbA+p0RkA0jQCONNuzNUY2cCKknhfufCrmR7SuLJZVuZqLXnQ5142xUBlg9hGw27G0G+RBC/ZebqPLDDWCiO9qmPUqOPvGmwwnOKP8YyekNcYqgFj9lPVZ5s+3FP5RnsxayvkewBShIRaUwgasaQLfWfIjLTTJP5D6OfblHRfDMn8n7H4sSY1JVg5eAvzWWh4PJcNVvjzekIRtcRcHp+cVDyD/zHcDximxCRCvRQqC/7C+MWoCptzFbEPz8CiT1ARxyAF7x0wqZ/+WfUDGgYIFfeWluyIMzs3b9LyZHMgPooFxj9L8T7v0Gp3uGnJEh20jHfAmLJsxRPTDWhCnORFuF/sYkFVFrGk8k/O+FCSQjFzuDbKL7nLrEte+FZGOmjUF9tGz8ni6TJBO2KnUG2zvFNN4gCmWAC34DQ="
    file: 
    - jvmtop
    - jvmtop.jar
    skip_cleanup: false
    on:
      tags: false
      repo: strapdata/jvmtop
